### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [harregoces/moodle-local_multiple_notifications#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by harregoces** [comment]
I have followed the instructions and set the privacy API according to the information you provide me.
@danmarsden As I understand I do not store any user data so I set the null_provider.
Thanks.
